TTC/urls.py
from django.urls import path
from . import views
#Adding
urlpatterns=[
    path('',views.index,name="index"),
    path('midway',views.midway,name="midway"),
    path('sampleSearch',views.searchRequest,name="Search"),
    path('sampleSearch_Employer',views.searchRequest_Employer,name="SearchEmployer"),
    path('home',views.home,name="home"),
    path('form_Employee',views.form_Employee,name="formE"),
    path('form_Employer',views.form_Employer,name="formEmployer"),
    path('EmployeePage',views.employee,name="employee"),
    path('EmployerPage',views.employer,name="employer")
]

The_Trojan_Cavalry/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('TTC.urls')),
    path('admin/', admin.site.urls)
]

TTC/models.py
from django.db import models

# Create your models here.
class Employer(models.Model):
    Employer_Name=models.CharField(max_length=300)
    location=models.CharField(max_length=300)
    Employer_PhNo=models.CharField(max_length=300)
    Employer_Email=models.EmailField(max_length=300)
    Employer_BizModel=models.CharField(max_length=300)

    def __str__(self):
        return self.Employer_Name

class Employee(models.Model):
    Employee_Name=models.CharField(max_length=300)
    
    Employee_PhNo=models.CharField(max_length=400)
    
    Emp_ID=models.IntegerField()

    Emp_Mail=models.EmailField(max_length=300)

    Emp_Job_Requirement=models.CharField(max_length=400)
    
    def __str__(self):
        return self.Employee_Name

TTC/views.py
from django.shortcuts import render
from TTC.models import Employee, Employer
from TTC.form_Employee import NewUser
from TTC.form_Employer import NewEmployer
from django.db import models
from django.http import HttpResponse
from django.core.paginator import Paginator
# Create your views here.


def midway(request):
    return render(request,'base3.html')

def index(request):
    return render(request,'base.html')
def home(request):
    e=Employee.objects.order_by('Employee_Name')
    dict1={'employee':e}
    return render(request,'home.html',context=dict1)

def employee(request):
    return render(request,'employee.html')

def employer(request):
    return render(request,'employee.html')

def form_Employee(request):

    form = NewUser()

    if request.method == "POST":
        form=NewUser(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

        else:
            print('ERROR FORM INVALID')

    return render(request, 'form_Employee.html',{'form':form})

def searchRequest(request):
    if request.method == 'POST':
        Entered_Request=request.POST.get('JobReqdfield',None)
        # for employees in Employee:
        #     if employee.Emp_ID == Entered_ID:
        #         return HttpResponse('employee.Employee_Name')
        try:
            user=Employee.objects.filter(Emp_Job_Requirement=Entered_Request)
            dict_2 = {'items':user}
            return render(request, 'sampleSearch.html', context=dict_2)
        except Employee.DoesNotExist:
            return HttpResponse("No object")
    else:
        return render(request, 'sampleSearch.html')

def form_Employer(request):

    form1 = NewEmployer()

    if request.method == "POST":
        form1=NewEmployer(request.POST)

        if form1.is_valid():
            form1.save(commit=True)
            return index(request)

        else:
            print('ERROR FORM INVALID')
    return render(request, 'form_Employer.html',{'form':form1})



def searchRequest_Employer(request):
    if request.method == 'POST':
        Entered_Request=request.POST.get('BizModelField',None)
        # for employees in Employee:
        #     if employee.Emp_ID == Entered_ID:
        #         return HttpResponse('employee.Employee_Name')
        try:
            user=Employer.objects.filter(BizModel=Entered_Request)
            dict_2 = {'items':user}
            return render(request, 'sampleSearch.html', context=dict_2)
        except Employer.DoesNotExist:
            return HttpResponse("No object")
    else:
        return render(request, 'sampleSearch_Employer.html')

templates/base3.html
<html>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        
      
    .button1 {
            border-radius: 12px;
            background-color: black;
            border: 2px solid #f5c400;
            text-align: center;
            color: #f5c400;
            font-size: 15px;
            padding: 50px;
            width: 200px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 100px;
           
          }
          
          .button1 span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
          }
          
          .button1 span:after {
            content: '\00bb';
            position: absolute;
            opacity: 0;
            top: 0;
            right: 0px;
            transition: 0.5s;
          }
          
          .button1:hover  {
            font-size: 50px;
            border: 0px;
            
            color: white;
          }
          .button1:hover span {
            font-size: 50px;
            border: 0px;
            
          }
          
          .button1:hover span:after {
            opacity: 1;
            right: 0;
          }
          div.center {
            position: fixed;
            right: 0px;
            left: 350px;
            top: 300px;
          }
          div.text {
            position: fixed;
            right: 0px;
            left: 450px;
            top: 150px;
          }
           p {
              color: white; 
              font-family: "Lucida Console", "Courier New", monospace;
               font-size: 50px;}
    
           
           .but2 {
             color: white;
             border: 0px solid;
             background-color: black;
             cursor: pointer;
           }


    div.ani {
            width: 8px; 
            height: 60px;
            background-color: red;
            position: relative;
            animation-name: anima;
            animation-duration: 4s;
            animation-iteration-count: infinite;
          }
          @keyframes anima {
            0%   {background-color:red; left:1026px; top:150px;width: 8px; height: 8px;}
            25%  {background-color:yellow; left:1026px; top:150px;width: 8px; height: 50px;}
            50%  {background-color:blue; lleft:1026px; top:150px;width: 8px; height: 30px;}
            75%  {background-color:green; left:1026px; top:150px;width: 8px; height: 50px;}
            100% {background-color:red; left:1026px; top:150px;width: 8px; height: 8px;}
          }
       
    </style>
    </head>
    <body bgcolor="black">
    
    <div class="text">
	<p>Welcome All Members.</P>
      </div>
      <div class="center">
      <a href="/sampleSearch"><button class="button1"><span>List of Businesses</span></button></a>
      <a href="/sampleSearch_Employer"><button class="button1"><span>List of Applicants</span></button></a>
      
      </div>
     	<div class="ani"></div>
      
       <div class="text"><a href="" target="_blank"><button class="but2">First Time? Sign Up</button></a></div>
     
</html>

templates/form_Employee.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      {{form.as_p}}
      {%csrf_token%}
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html>
 -->
<!-- 
 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      <p><label for="id_Employee_Name">Employee Name:</label> <input type="text" name="Employee_Name" maxlength="300" required id="id_Employee_Name"></p>
<p><label for="id_Employee_PhNo">Employee PhNo:</label> <input type="text" name="Employee_PhNo" maxlength="400" required id="id_Employee_PhNo"></p>
<p><label for="id_Emp_ID">Emp ID:</label> <input type="number" name="Emp_ID" required id="id_Emp_ID"></p>
<p><label for="id_Emp_Mail">Emp Mail:</label> <input type="email" name="Emp_Mail" maxlength="300" required id="id_Emp_Mail"></p>
<p><label for="id_Emp_Job_Requirement">Emp Job Requirement:</label> <input type="text" name="Emp_Job_Requirement" maxlength="400" required id="id_Emp_Job_Requirement"></p>
      <input type="hidden" name="csrfmiddlewaretoken" value="9TfsCxzkI7L809pg4mRsL6ZjKVvnaf0InN49cW9Hd6o1DristcqayzDYzGhoYlhX">
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html>
 -->


 <!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      {{form.as_p}}
      {%csrf_token%}
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html>
 -->

 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EMPLOYER FORM</title>
        <link rel="stylesheet" href="style.css" type="text/css">
        <style>
            h1 {
                color: #f5c400;
                font-size: 70px;
                margin-left: 100px;
                font-family: Helvetica;
            }
            label{
                color: white;
            }
            input {
                background-color: black;
                border: 2px solid #f5c400;
                border-radius: 30px;
                padding: 20px 80px 12px 10px;
                font-family: Helvetica;
               color: #f5c400;
               margin: 20px 50px 20px 50px;
               padding: 20px 100px 10px 100px;
                
            }
            
            div.sub {
                 color:  #f5c400;
                 position: relative;
                 left: 200px;
                 top: 15px;
        
            }
            label {
                font-family: Helvetica;
            }
            div.register {
                position: fixed;
                top: 100px;
                left: 400px;
            }
            .button {
                border-radius: 30px;
                background-color: black;
                border: 2px solid #f5c400;
                text-align: center;
                color: #f5c400;
                font-size: 20px;
                padding: 15px;
                width: 200px;
                transition: all 0.5s;
                cursor: pointer;
                margin-left:500px;
              }
              
              .button span {
                cursor: pointer;
                display: inline-block;
                position: relative;
                transition: 0.5s;
              }
              
              .button span:after {
                content: '\00bb';
                position: absolute;
                opacity: 0;
                top: 0;
                right: -20px;
                transition: 0.5s;
              }
              
              .button:hover  {
                font-size: 25px;
                background-color: #f5c400;
                color: rgb(255, 255, 255);
              }
              .button:hover span {
                padding-right: 25px;
                
              }
              
              .button:hover span:after {
                opacity: 1;
                right: 0;
              }
          </style>
    </head>
<body bgcolor="black">
  <h1>Sign Up</h1>
  <div class="register">
  <form method="POST">
      <p><label for="id_Employee_Name">Employee Name: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employee_Name" maxlength="300" required id="id_Employee_Name"></p>
<p><label for="id_Employee_PhNo">Employee PhNo:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employee_PhNo" maxlength="400" required id="id_Employee_PhNo"></p>
<p><label for="id_Emp_ID">Emp ID:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="number" name="Emp_ID" required id="id_Emp_ID"></p>
<p><label for="id_Emp_Mail">Emp Mail: &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="email" name="Emp_Mail" maxlength="300" required id="id_Emp_Mail"></p>
<p><label for="id_Emp_Job_Requirement">Emp Job Requirement:</label> <input type="text" name="Emp_Job_Requirement" maxlength="400" required id="id_Emp_Job_Requirement"></p>
      <input type="hidden" name="csrfmiddlewaretoken" value="9TfsCxzkI7L809pg4mRsL6ZjKVvnaf0InN49cW9Hd6o1DristcqayzDYzGhoYlhX">
      
  </form>
  <div class="sub"><button class="button">SUBMIT</button></div>
</div>
  
</body>
</html>

templates/form_Employer.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      {{form.as_p}} -->
      <!-- <p><label for ="id_EmployeeName">Employer_Name</label>
          <input id="id_EmployeeName" name="Employer Name">
        </p> -->
      <!-- {%csrf_token%}
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html> -->

<!-- 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      <p><label for="id_Employer_Name">Employer Name:</label> <input type="text" name="Employer_Name" maxlength="300" required id="id_Employer_Name"></p>
<p><label for="id_location">Location:</label> <input type="text" name="location" maxlength="300" required id="id_location"></p>
<p><label for="id_Employer_PhNo">Employer PhNo:</label> <input type="text" name="Employer_PhNo" maxlength="300" required id="id_Employer_PhNo"></p>
<p><label for="id_Employer_Email">Employer Email:</label> <input type="email" name="Employer_Email" maxlength="300" required id="id_Employer_Email"></p>
<p><label for="id_Employer_BizModel">Employer BizModel:</label> <input type="text" name="Employer_BizModel" maxlength="300" required id="id_Employer_BizModel"></p>
       <p><label for ="id_EmployeeName">Employer_Name</label>
          <input id="id_EmployeeName" name="Employer Name">
        </p> -->
      <!-- <input type="hidden" name="csrfmiddlewaretoken" value="Ubmk5hVSm2vqG0putjdNUhgI33Qhelhq85b1FGvfR18jjiiGS9MvHKUnSOCi2ryF">
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html> -->
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      {{form.as_p}} -->
      <!-- <p><label for ="id_EmployeeName">Employer_Name</label>
          <input id="id_EmployeeName" name="Employer Name">
        </p> -->
      <!-- {%csrf_token%}
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html> -->


<!DOCTYPE html>
<html lang="en">
        <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>EMPLOYER FORM</title>
                <link rel="stylesheet" href="style.css" type="text/css">
                <style>
                    h1 {
                        color: #f4511e;
                        font-size: 70px;
                        margin-left: 100px;
                        font-family: Helvetica;
                    }
                    label{
                        color: white;
                    }
                    input {
                        background-color: black;
                        border: 2px solid #f4511e;
                        border-radius: 30px;
                        padding: 20px 80px 12px 10px;
                        font-family: Helvetica;
                       color: #f4511e;
                       margin: 20px 50px 20px 50px;
                       padding: 20px 100px 10px 100px;
                        
                    }
                    
                    div.sub {
                         color:  #f4511e;
                         position: relative;
                         left: 200px;
                         top: 15px;
                
                    }
                    label {
                        font-family: Helvetica;
                    }
                    div.register {
                        position: fixed;
                        top: 100px;
                        left: 400px;
                    }
                    .button {
                        border-radius: 30px;
                        background-color: black;
                        border: 2px solid #f4511e;
                        text-align: center;
                        color: #f4511e;
                        font-size: 20px;
                        padding: 15px;
                        width: 200px;
                        transition: all 0.5s;
                        cursor: pointer;
                        margin-left:500px;
                      }
                      
                      .button span {
                        cursor: pointer;
                        display: inline-block;
                        position: relative;
                        transition: 0.5s;
                      }
                      
                      .button span:after {
                        content: '\00bb';
                        position: absolute;
                        opacity: 0;
                        top: 0;
                        right: -20px;
                        transition: 0.5s;
                      }
                      
                      .button:hover  {
                        font-size: 25px;
                        background-color: #f4511e;
                        color: rgb(255, 255, 255);
                      }
                      .button:hover span {
                        padding-right: 25px;
                        
                      }
                      
                      .button:hover span:after {
                        opacity: 1;
                        right: 0;
                      }
                  </style>
            </head>
<body bgcolor="black">
  <h1>SIGN UP</h1>
  <div class="register">
  <form method="POST">
      <p><label for="id_Employer_Name">Employer Name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employer_Name" maxlength="300" required id="id_Employer_Name"></p>
<p><label for="id_location">Location:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="location" maxlength="300" required id="id_location"></p>
<p><label for="id_Employer_PhNo">Employer PhNo:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employer_PhNo" maxlength="300" required id="id_Employer_PhNo"></p>
<p><label for="id_Employer_Email">Employer Email: &nbsp;&nbsp; &nbsp;</label> <input type="email" name="Employer_Email" maxlength="300" required id="id_Employer_Email"></p>
<p><label for="id_Employer_BizModel">Employer BizModel:</label> <input type="text" name="Employer_BizModel" maxlength="300" required id="id_Employer_BizModel"></p>
      <!-- <p><label for ="id_EmployeeName">Employer_Name</label>
          <input id="id_EmployeeName" name="Employer Name">
        </p> -->
      <input type="hidden" name="csrfmiddlewaretoken" value="Ubmk5hVSm2vqG0putjdNUhgI33Qhelhq85b1FGvfR18jjiiGS9MvHKUnSOCi2ryF">
      <div class="sub"><button class="button">SUBMIT</button></div>
  </form>
  </div>div>
</body>
</html>

templates/form_employee.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      {{form.as_p}}
      {%csrf_token%}
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html>
 -->

 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EMPLOYER FORM</title>
        <link rel="stylesheet" href="style.css" type="text/css">
        <style>
            h1 {
                color: #f5c400;
                font-size: 70px;
                margin-left: 100px;
                font-family: Helvetica;
            }
            label{
                color: white;
            }
            input {
                background-color: black;
                border: 2px solid #f5c400;
                border-radius: 30px;
                padding: 20px 80px 12px 10px;
                font-family: Helvetica;
               color: #f5c400;
               margin: 20px 50px 20px 50px;
               padding: 20px 100px 10px 100px;
                
            }
            
            div.sub {
                 color:  #f5c400;
                 position: relative;
                 left: 200px;
                 top: 15px;
        
            }
            label {
                font-family: Helvetica;
            }
            div.register {
                position: fixed;
                top: 100px;
                left: 400px;
            }
            .button {
                border-radius: 30px;
                background-color: black;
                border: 2px solid #f5c400;
                text-align: center;
                color: #f5c400;
                font-size: 20px;
                padding: 15px;
                width: 200px;
                transition: all 0.5s;
                cursor: pointer;
                margin-left:500px;
              }
              
              .button span {
                cursor: pointer;
                display: inline-block;
                position: relative;
                transition: 0.5s;
              }
              
              .button span:after {
                content: '\00bb';
                position: absolute;
                opacity: 0;
                top: 0;
                right: -20px;
                transition: 0.5s;
              }
              
              .button:hover  {
                font-size: 25px;
                background-color: #f5c400;
                color: rgb(255, 255, 255);
              }
              .button:hover span {
                padding-right: 25px;
                
              }
              
              .button:hover span:after {
                opacity: 1;
                right: 0;
              }
          </style>
    </head>
<body bgcolor="black">
  <h1>Sign Up</h1>
  <div class="register">
  <form method="POST">
      <p><label for="id_Employee_Name">Employee Name: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employee_Name" maxlength="300" required id="id_Employee_Name"></p>
<p><label for="id_Employee_PhNo">Employee PhNo:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employee_PhNo" maxlength="400" required id="id_Employee_PhNo"></p>
<p><label for="id_Emp_ID">Emp ID:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="number" name="Emp_ID" required id="id_Emp_ID"></p>
<p><label for="id_Emp_Mail">Emp Mail: &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="email" name="Emp_Mail" maxlength="300" required id="id_Emp_Mail"></p>
<p><label for="id_Emp_Job_Requirement">Emp Job Requirement:</label> <input type="text" name="Emp_Job_Requirement" maxlength="400" required id="id_Emp_Job_Requirement"></p>
      <input type="hidden" name="csrfmiddlewaretoken" value="9TfsCxzkI7L809pg4mRsL6ZjKVvnaf0InN49cW9Hd6o1DristcqayzDYzGhoYlhX">
      
  </form>
  <div class="sub"><button class="button">SUBMIT</button></div>
</div>
  
</body>
</html>

templates/form_employer.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Lets sign up</h1>
  <form method="POST">
      {{form.as_p}} -->
      <!-- <p><label for ="id_EmployeeName">Employer_Name</label>
          <input id="id_EmployeeName" name="Employer Name">
        </p> -->
      <!-- {%csrf_token%}
      <input type="submit" name="" value="submit">
  </form>
  
</body>
</html> -->


<!DOCTYPE html>
<html lang="en">
        <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>EMPLOYER FORM</title>
                <link rel="stylesheet" href="style.css" type="text/css">
                <style>
                    h1 {
                        color: #f4511e;
                        font-size: 70px;
                        margin-left: 100px;
                        font-family: Helvetica;
                    }
                    label{
                        color: white;
                    }
                    input {
                        background-color: black;
                        border: 2px solid #f4511e;
                        border-radius: 30px;
                        padding: 20px 80px 12px 10px;
                        font-family: Helvetica;
                       color: #f4511e;
                       margin: 20px 50px 20px 50px;
                       padding: 20px 100px 10px 100px;
                        
                    }
                    
                    div.sub {
                         color:  #f4511e;
                         position: relative;
                         left: 200px;
                         top: 15px;
                
                    }
                    label {
                        font-family: Helvetica;
                    }
                    div.register {
                        position: fixed;
                        top: 100px;
                        left: 400px;
                    }
                    .button {
                        border-radius: 30px;
                        background-color: black;
                        border: 2px solid #f4511e;
                        text-align: center;
                        color: #f4511e;
                        font-size: 20px;
                        padding: 15px;
                        width: 200px;
                        transition: all 0.5s;
                        cursor: pointer;
                        margin-left:500px;
                      }
                      
                      .button span {
                        cursor: pointer;
                        display: inline-block;
                        position: relative;
                        transition: 0.5s;
                      }
                      
                      .button span:after {
                        content: '\00bb';
                        position: absolute;
                        opacity: 0;
                        top: 0;
                        right: -20px;
                        transition: 0.5s;
                      }
                      
                      .button:hover  {
                        font-size: 25px;
                        background-color: #f4511e;
                        color: rgb(255, 255, 255);
                      }
                      .button:hover span {
                        padding-right: 25px;
                        
                      }
                      
                      .button:hover span:after {
                        opacity: 1;
                        right: 0;
                      }
                  </style>
            </head>
<body bgcolor="black">
  <h1>SIGN UP</h1>
  <div class="register">
  <form method="POST">
      <p><label for="id_Employer_Name">Employer Name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employer_Name" maxlength="300" required id="id_Employer_Name"></p>
<p><label for="id_location">Location:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="location" maxlength="300" required id="id_location"></p>
<p><label for="id_Employer_PhNo">Employer PhNo:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="Employer_PhNo" maxlength="300" required id="id_Employer_PhNo"></p>
<p><label for="id_Employer_Email">Employer Email: &nbsp;&nbsp; &nbsp;</label> <input type="email" name="Employer_Email" maxlength="300" required id="id_Employer_Email"></p>
<p><label for="id_Employer_BizModel">Employer BizModel:</label> <input type="text" name="Employer_BizModel" maxlength="300" required id="id_Employer_BizModel"></p>
      <!-- <p><label for ="id_EmployeeName">Employer_Name</label>
          <input id="id_EmployeeName" name="Employer Name">
        </p> -->
      <input type="hidden" name="csrfmiddlewaretoken" value="Ubmk5hVSm2vqG0putjdNUhgI33Qhelhq85b1FGvfR18jjiiGS9MvHKUnSOCi2ryF">
      <div class="sub"><button class="button">SUBMIT</button></div>
  </form>
  </div>div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Hello Welcome to page</h1>
    <!--To eliminate the below tag display-->
{% if employee %}
    <table border=5px>
        <thead>
            <th>Name</th>
            <th>PhNo</th>
            <th>Applicant_ID</th>
            <th>Applicant_Email</th>
            <th>Description</th>
        </thead>

    {%for emp in employee%}
    <tr>
        <td>{{emp.Employee_Name}}</td>
        <td>{{emp.Employee_PhNo}}</td>
        <td>{{emp.Emp_ID}}<td>
        <td>{{emp.Emp_Mail}}<td>
        <td>{{emp.Emp_Job_Requirement}}</td>            
        <p></p>
    </tr>
    {%endfor%}
    </table>
 {% endif %}
</body>
</html>

<!-- {% block body %} -->
<!--{% endblock body %} -->